# Generated by Django 2.0.6 on 2019-09-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=10, null=True)),
                ('vehicle_id', models.CharField(max_length=10, null=True)),
                ('alert_type', models.CharField(max_length=10, null=True)),
                ('priority', models.CharField(max_length=10, null=True)),
                ('contact_no', models.CharField(max_length=10, null=True)),
                ('action', models.CharField(max_length=10, null=True)),
                ('latitude', models.CharField(max_length=10, null=True)),
                ('longtude', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
