# Generated by Django 2.0.5 on 2019-11-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=10, null=True)),
                ('end', models.CharField(max_length=10, null=True)),
                ('vehicle', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
