# Generated by Django 2.0.6 on 2019-09-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='speed',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
