# Generated by Django 2.0.5 on 2019-11-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_auto_20190925_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='speed',
            field=models.IntegerField(null=True),
        ),
    ]
