# Generated by Django 2.0.5 on 2019-11-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_auto_20190917_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_Name', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(max_length=80, null=True)),
            ],
        ),
    ]
